#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Recipizer.Resource", IsApplication=true)]

namespace Recipizer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int absoluteLayout1 = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int absoluteLayoutRecipes = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int btnAddIngredient = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int btnAddShopIngredient = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int btnCreateRecipe = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int btnEditList = 2131034118;
			
			// aapt resource value: 0x7f050017
			public const int btnEditRecipe = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int btnMealPlanNav = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int btnNewRecipe = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int btnRecipeNav = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int btnSaveEdit = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int btnSettingsNav = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int btnShopListNav = 2131034124;
			
			// aapt resource value: 0x7f050016
			public const int linearLayout1 = 2131034134;
			
			// aapt resource value: 0x7f050000
			public const int linearLayoutIngredient = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int listIngredients = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int listViewIngredients = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int listViewRecipes = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int listViewShoppingList = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int spinnerUnits = 2131034115;
			
			// aapt resource value: 0x7f050015
			public const int textEditRecipeDescription = 2131034133;
			
			// aapt resource value: 0x7f050002
			public const int textIngredientAmount = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int textIngredientName = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int textRecipeDescription = 2131034119;
			
			// aapt resource value: 0x7f050013
			public const int textRecipeName = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int CreateRecipe = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Recipes = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ShoppingList = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ViewRecipe = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030009
			public const int btn_add = 2130903049;
			
			// aapt resource value: 0x7f030008
			public const int btn_create = 2130903048;
			
			// aapt resource value: 0x7f030006
			public const int btn_edit = 2130903046;
			
			// aapt resource value: 0x7f030002
			public const int btn_mealPlanNav_main = 2130903042;
			
			// aapt resource value: 0x7f030005
			public const int btn_newRecipe_recipes = 2130903045;
			
			// aapt resource value: 0x7f030001
			public const int btn_recipeNav_main = 2130903041;
			
			// aapt resource value: 0x7f030007
			public const int btn_save = 2130903047;
			
			// aapt resource value: 0x7f030004
			public const int btn_settingsNav_main = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int btn_shopListNav_main = 2130903043;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Theme_Custom = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
